pharos:
    metrics_collect_interval: 1
    storage_type: mongodb
    lighttower:
        lighttower_host: localhost
        lgihttower_event_boradcast_port: 4242
        lighttower_event_collect_port: 4343
        lighttower_remote_api_port: 4444

    lightkeeper:
        lightkeeper_rpc_port: 5555

docker:
    docker_bridge_ip: 172.17.42.1
    docker_unix_socket_path: /var/run/docker.sock
    docker_remote_api_port: 2375
    docker_api_version: v1.14

mongodb:
    mongos_port: 27017

